### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by JoeSGT** [Timardo/Thermos#1]
Hello i was wondering are you going to continue this thermos project? if so are you going to setup a discord or something ?

**Comment by Timardo** [comment]
Well, I am doing this because I am starting my own server and I just wanted to share "fixes" on some issues like the one with NMS and NBT stuff. But I am not a programmer so I don't know if I can handle big problems this project have. And discord.. I am on CyberDyne's one so making own Discord server is unnecessary.

All in all, I am just learning with this project, so don't expect miracles.

**Comment by JoeSGT** [comment]
ohh okay thanks you very very much for sharing your fixes <3
